version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: orbital_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orbital_eletronicos
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: orbital_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orbital_eletronicos
      JWT_SECRET: admin_orbital_0307
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src

volumes:
  mysql_data: